### ISSUE TITLE
WG hard Bug Cant make Veichles!!

### ISSUE THREAD

**Issue by spana1993** [OmegaWoWeu/Decades#109] opened 2019-03-08 19:21 UTC
Horde Cant build veichles in WG!
-1/8 wtf? :)
pic.: https://imgur.com/a/kMAvJws

Castiel

**Comment by blzee** [comment] 2019-03-09 19:54
Not enough info was provided within the report, also most likely a client side visual error, delete your cache. Closing, if the issue is brought up again then it will be investigated.

**Closed as completed by blzee** 2019-03-09 19:54 UTC
