### ISSUE TITLE
Enhance Shamans stacking spellpower weapons / gear due to bug

### ISSUE THREAD

**Issue by Dolice1990** [OmegaWoWeu/Decades#219] opened 2019-06-09 20:59 UTC
Description: There is an enhance shaman in our guild stacking spellpower weapons and doing absurd dps compared to what enhance shamans should be doing

How to reproduce bug: stack spellpower on enhance shaman gear with a spellpower MH

How it should work: they should be doing way less dps than 8k dps and 12k dps on xt heart

Screenshots: https://ibb.co/drSHjV2

Relevant AddOns used: Recount

Source: http://forum.warmane.com/showthread.php?t=311020&page=2

stop this bug before the toc trinket reign of the dead becomes bis for enhance shaman and they end up doing 19k dps in toc

**Comment by MarceloTheOne** [comment] 2019-06-10 00:31
Could you tell me exactly which spells are dealing too much damage?

**Comment by Dolice1990** [comment] 2019-06-10 02:06
flametonge weapon, frostbrand weapon, fire nova

source: https://www.reddit.com/r/KronosWoW/comments/99mpc0/another_way_to_play_enhancement_shaman/ (i know it's a vanilla wow post)

currently the shaman in question is saying Valanyr is his BIS weapon in ulduar due to this bug, which is really fucked since as you well know it's ment to be a healer item

________________________________

**Comment by Dolice1990** [comment] 2019-06-10 02:10
i'll post screenshots of his recount next weekend when we raid to see what you can make of it

**Comment by Dolice1990** [comment] 2019-06-10 17:19
https://ibb.co/L5yjzMj from yogg 25 yesterday, sadly don't have any more, will get more next week

**Comment by Rugsz** [comment] 2019-06-11 21:44
I've seen this guy before and I've heard of shamans doing this on other servers. It's my understanding that this "bug" is consistent. Consistency would lead me to believe that this is how it was back in 3.3.5 and nothing is wrong about it.

**Comment by goodplayer123** [comment] 2019-06-11 22:29
not bugged. the reason this build is strong is because fire nova was a totem and not a spell before 3.3, and in icc the amount of raw AP you get will outshine a double flametongue build so this was never relevant on retail. it's only a thing on progressive wotlk servers running 3.3.5. the only 'fix' for this would be running a 3.0 client which no one will ever do because it's too much work. 
the trinket however i don't know because i've never played this build in toc+ (hehe we did icc together on sunwell). maybe the proc coefficient is bugged, but that's another discussion.

**Comment by goodplayer123** [comment] 2019-06-11 22:50
about flametongue: 

Flametongue is normalised based on a 4.0 speed weapon. The values are 

float damageFTBase = 274f * cs.UnhastedOHSpeed / 4.0f;
float damageFTCoef = 0.03811f * cs.UnhastedOHSpeed;

ie: base FT damage is 274 * tooltip weaponspeed/4, and spellpower coefficient is 0.03811 * tooltip weaponspeed.


this is from an old EJ post

0.03811 * tooltip weaponspeed.
with a 2.7 weapon flametongue attacks would gain 10% sp scaling
at 3k spell power that's an extra 300 damage per flametongue attack before modifiers

also i'm not using frostbrand dunno where you got that from

honestly not sure what you're getting at with that reddit link either

**Comment by DollpartsFTP** [comment] 2019-06-12 00:16
So after being linked this by 5-6 different Bull Up users blaming me for creating it, I decided to make a github account to comment.

Not a bug, spell power enhance is a thing. It got tested on Warmane many many times and has been a staple way to play enhance ever since. Frankly him saying legendary mace is bis is legit for spell power.. But more likely he'll use Aesuga from Vezax 10.

Leave the guy alone, he's not "breaking the game" and this isn't a bug. He's doing about the DPS enhancers should do using any of the build and this thread is because of the reputation enhance has as a "bad spec".

**Comment by DollpartsFTP** [comment] 2019-06-12 00:20
I actually tested it out on the Ulduar PTr and the only reason i didn't want to play it is because the competition for gear is high and i didn't enjoy the playstyle..

**Comment by Dolice1990** [comment] 2019-06-12 02:03
after talking with a few members from prime it seems that he was talking about spellpower scaling in general is off, the shaman in prime mentioned he was using the normal WF MH, FT OH combo and his recount damage list comes in like this Melee, WF wep, Flametongue, lightning bolt then lightning shield, i mentioned frostbrand from a previous source of someone else talking about the build linked above and wasn't saying anyone was using it just as a note of reference of what needs testing. The fact is enhance was one one of the lowest dps classes in ICC from various sources of average dps back on live from an old source on mmo champion https://www.mmo-champion.com/threads/752517-Comparison-of-DPS-classes  more than likely though the enhance shamans in that list wasn't using a Spellpower MH like you were doing, there's no way to know for sure, nobody that plays enhance shaman suddenly comes the conclusion that using a spellpower MH is better to use than a normal slow agility weapon MH  so theres obviously something not right since the normal Enhance shaman class since TBC has used a Slow agi MH there are many bugs persistent through private servers as most of them use the same core, that doesn't mean it's working as intended even if Spellpower weapon in MH is consistent on most wotlk private servers

**Comment by kingkrule** [comment] 2019-06-12 05:34
It was explained to you that this is not a bug. 

"fire nova was a totem and not a spell before 3.3, and in icc the amount of raw AP you get will outshine a double flametongue build so this was never relevant on retail. it's only a thing on progressive wotlk servers running 3.3.5. the only 'fix' for this would be running a 3.0 client." 

Just by skimming your reply, it's pretty clear you did not actually read goodplayer123's post.

**Comment by DollpartsFTP** [comment] 2019-06-12 06:56
I actually played Enhancement on retail in WOTLK(as an alt, mind) and it was NOT one of the lowest DPS classes in ICC, nor any other patch really. It's just a tough spec to play well and suffers from the devastatingly crippling "Low health syndrome". The output has never been what makes enhancement a bad spec.

But as mentioned, what he's doing isn't a bug and the damage you mentioned really isn't that huge. Bursting 12k on the heart at XT isn't that rough (We're a class that literally specialises in short area burst), and my average DPS on XT has been between 8-9.5k full fight (Which i told you when you whispered me this stuff).

Just because somebody is doing good damage on a "bad spec" doesn't mean he's cheating, nor does it mean it's bugged.

If you wanna bring up Feral Spirits not getting our AP properly though, now that's bugged.. 14.5k on target dummy naked(527ap). 15k with 4499k AP, go figure, 4000 ap results in 500 more damage.

**Comment by Dolice1990** [comment] 2019-06-12 08:04
i have read every post and i don't care about fire nova that much again my point is there's obviously something wrong since you don't suddenly go "lets use a SP MH to see if i do more dps" the class in general is supposed to be played with 2 slow agility weapons, at least that's the concept blizzard wanted the class to be played like, that's like saying to a hunter, rogue or frost dk "lets test a spellpower MH to see if i do more dps" just because some of there abilities / poisons scale off spellpower somewhat, an enhance shaman in retail seen to be doing that would of been ridiculed by raid members etc  because it isn't common, the class isn't supposed to be played that way according to blizzard design philosophy of the class so something must be off, I remember it being a thing that every shaman was doing it on molten wow (old warmane) along with ret paladins using seal of command on single target boss fights because both were doing insane dps, soc was doing 3x the damage of what it was supposed to and enhance shamans were doing around 22k dps which both was later fixed, i might be wrong and it might not be a bug but it still needs looking into as it's not common to see a Enhance shaman use a Spellpower MH and do decent dps

**Comment by DollpartsFTP** [comment] 2019-06-12 09:31
It's not like somebody just said "let's try a spell power main hand".. this was tested, a LOT. Even with double physical weapons my damage split is 55:45 Physical:Spell.. They tested it initially with full spell power gear with enhance spec, then with physical gear and spell power weapon but with spell power gems etc. It was taken through the ringer over YEARS of testing it, it's not like it sprung up instantly and from nowhere.

you need to understand, also, that he might be using fire nova glyph (Which i'm not, currently as i don't have enough haste/other stats to warrant it as physical build), but this means he would have a fire nova every 2 seconds if he wanted it. Significantly changing his priority list. For example of this, for my priority list with physical build, fire nova is my "filler", out prioritising nothing but lava lash.. In the spell power build, it moves all the way up to number 2/3 on the priority list, outprioritising even stormstrike. and only being behind 5 maelstrom lightning bolt, totem and possibly lightning shield.

It changes a lot, so comparing my top 1-6 damaging abilities to his isn't really viable, as they're gonna be very very different.

**Comment by DollpartsFTP** [comment] 2019-06-12 09:32
In reply to the last post, SP Unholy DK did get tested and did good damage :P just not as good as the enhance version.

**Comment by Dolice1990** [comment] 2019-06-12 17:42
at this point i'm just going to leave it up to the devs to decide, i know damage numbers can be off since were playing with 3.3.5a buffed / nerfed talents in a 3.1.0 raid tier and the only "fix" for the error is to do progression by patch reverting talents, spells etc to what they should be in the current patch raid tier but that's too much work and near impossible to do correctly, the fact fire nova is in the single target rotation should tell you right away something isn't right, but again that could be because of the talents / spells being 3.5 and not 3.1

**Comment by MarceloTheOne** [comment] 2019-06-13 15:32
Too much work to correct such things every patch, won't be fixed.

**Closed as completed by MarceloTheOne** 2019-06-13 15:32 UTC
Labels: wontfix
